name: LPR Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Pull code from GitHub vault
        uses: actions/checkout@v4

      # keys
      - name: Configure credentials for AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 
      # login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # build, tag, and push image to ECR
      - name: Build, tag, and push image
        env:
          # ECR_REGISTRY is available in the login-ecr step output
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: lpr-api
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG